pub const INPUT1: &str = "............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............";
pub const OUTPUT1: usize = 14;

pub const INPUT2: &str = INPUT1;
pub const OUTPUT2: usize = 34;
